var searchData=
[
  ['userevent',['UserEvent',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_event.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['usergender',['UserGender',['../struct_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_gender.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userinfo_5fpublic',['UserInfo_Public',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_info___public.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userservexternal_5fgetplayinguserinfo_5fargs',['UserServExternal_GetPlayingUserInfo_args',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_serv_external___get_playing_user_info__args.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userservexternal_5fgetplayinguserinfo_5fpargs',['UserServExternal_GetPlayingUserInfo_pargs',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_serv_external___get_playing_user_info__pargs.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userservexternal_5fgetplayinguserinfo_5fpresult',['UserServExternal_GetPlayingUserInfo_presult',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_serv_external___get_playing_user_info__presult.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userservexternal_5fgetplayinguserinfo_5fresult',['UserServExternal_GetPlayingUserInfo_result',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_serv_external___get_playing_user_info__result.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userservexternalclient',['UserServExternalClient',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_serv_external_client.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userservexternalconcurrentclient',['UserServExternalConcurrentClient',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_serv_external_concurrent_client.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userservexternalhandler',['UserServExternalHandler',['../class_user_serv_external_handler.html',1,'']]],
  ['userservexternalif',['UserServExternalIf',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_serv_external_if.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userservexternaliffactory',['UserServExternalIfFactory',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_serv_external_if_factory.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userservexternalifsingletonfactory',['UserServExternalIfSingletonFactory',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_serv_external_if_singleton_factory.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userservexternalmultiface',['UserServExternalMultiface',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_serv_external_multiface.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userservexternalnull',['UserServExternalNull',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_serv_external_null.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userservexternalprocessor',['UserServExternalProcessor',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_serv_external_processor.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userservexternalprocessorfactory',['UserServExternalProcessorFactory',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_serv_external_processor_factory.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userserviceexternalsdkdatatypesconstants',['UserServiceExternalSDKDataTypesConstants',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_service_external_s_d_k_data_types_constants.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['userserviceexternalsdkservicesconstants',['UserServiceExternalSDKServicesConstants',['../class_ruyi_1_1_s_d_k_1_1_user_service_external_1_1_user_service_external_s_d_k_services_constants.html',1,'Ruyi::SDK::UserServiceExternal']]],
  ['usertype',['UserType',['../struct_ruyi_1_1_s_d_k_1_1_common_type_1_1_user_type.html',1,'Ruyi::SDK::CommonType']]]
];
