var searchData=
[
  ['validatesdk',['ValidateSDK',['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service_if.html#a487ba1cc328fb36a5a735632d1482595',1,'Ruyi::SDK::SDKValidator::ValidatorServiceIf::ValidateSDK()'],['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service_null.html#ae4f8410312f4667aa5aeaa3507ebe621',1,'Ruyi::SDK::SDKValidator::ValidatorServiceNull::ValidateSDK()'],['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service_client.html#a8a49554f1b177adcf266dcc51a28c664',1,'Ruyi::SDK::SDKValidator::ValidatorServiceClient::ValidateSDK()'],['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service_multiface.html#a8cf9c9ec5e2570733e348b8ce6b88d60',1,'Ruyi::SDK::SDKValidator::ValidatorServiceMultiface::ValidateSDK()'],['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service_concurrent_client.html#a4d32893a290781f4c40b9ffebcc3cf28',1,'Ruyi::SDK::SDKValidator::ValidatorServiceConcurrentClient::ValidateSDK()'],['../class_validator_service_handler.html#abcea7b8041a2df7646c146e068472674',1,'ValidatorServiceHandler::ValidateSDK()']]],
  ['validatorservice_5fvalidatesdk_5fargs',['ValidatorService_ValidateSDK_args',['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service___validate_s_d_k__args.html#a7acb2d014e35c6af48106d70ce0177eb',1,'Ruyi::SDK::SDKValidator::ValidatorService_ValidateSDK_args::ValidatorService_ValidateSDK_args(const ValidatorService_ValidateSDK_args &amp;)'],['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service___validate_s_d_k__args.html#aebf9955c6bcd4a9e743f9550cef2cac7',1,'Ruyi::SDK::SDKValidator::ValidatorService_ValidateSDK_args::ValidatorService_ValidateSDK_args()']]],
  ['validatorservice_5fvalidatesdk_5fresult',['ValidatorService_ValidateSDK_result',['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service___validate_s_d_k__result.html#a38267e9e97ef19001860183a6ed2ee2f',1,'Ruyi::SDK::SDKValidator::ValidatorService_ValidateSDK_result::ValidatorService_ValidateSDK_result(const ValidatorService_ValidateSDK_result &amp;)'],['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service___validate_s_d_k__result.html#ab9f6be8d48ff348dcd1c1a8fc5a9009c',1,'Ruyi::SDK::SDKValidator::ValidatorService_ValidateSDK_result::ValidatorService_ValidateSDK_result()']]],
  ['validatorserviceclient',['ValidatorServiceClient',['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service_client.html#a44c6b34ab50e7632c4a2cbbaa613c50f',1,'Ruyi::SDK::SDKValidator::ValidatorServiceClient::ValidatorServiceClient(apache::thrift::stdcxx::shared_ptr&lt; ::apache::thrift::protocol::TProtocol &gt; prot)'],['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service_client.html#a805a7f772637529451df761c51400afa',1,'Ruyi::SDK::SDKValidator::ValidatorServiceClient::ValidatorServiceClient(apache::thrift::stdcxx::shared_ptr&lt; ::apache::thrift::protocol::TProtocol &gt; iprot, apache::thrift::stdcxx::shared_ptr&lt; ::apache::thrift::protocol::TProtocol &gt; oprot)']]],
  ['validatorserviceconcurrentclient',['ValidatorServiceConcurrentClient',['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service_concurrent_client.html#abd640a5882c1b06fdd404911b381c6c8',1,'Ruyi::SDK::SDKValidator::ValidatorServiceConcurrentClient::ValidatorServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr&lt; ::apache::thrift::protocol::TProtocol &gt; prot)'],['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service_concurrent_client.html#ae7d4fe5ac953187b0edd7ab8a1c6fa46',1,'Ruyi::SDK::SDKValidator::ValidatorServiceConcurrentClient::ValidatorServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr&lt; ::apache::thrift::protocol::TProtocol &gt; iprot, apache::thrift::stdcxx::shared_ptr&lt; ::apache::thrift::protocol::TProtocol &gt; oprot)']]],
  ['validatorservicehandler',['ValidatorServiceHandler',['../class_validator_service_handler.html#acd3544fcc15d19cae5002eba1111483c',1,'ValidatorServiceHandler']]],
  ['validatorserviceifsingletonfactory',['ValidatorServiceIfSingletonFactory',['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service_if_singleton_factory.html#a79735aaedd8091fc6d59affdd46e98f5',1,'Ruyi::SDK::SDKValidator::ValidatorServiceIfSingletonFactory']]],
  ['validatorservicemultiface',['ValidatorServiceMultiface',['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service_multiface.html#aa392cd70e5578034d090248e9e5b8149',1,'Ruyi::SDK::SDKValidator::ValidatorServiceMultiface::ValidatorServiceMultiface(std::vector&lt; apache::thrift::stdcxx::shared_ptr&lt; ValidatorServiceIf &gt; &gt; &amp;ifaces)'],['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service_multiface.html#abd1fb90ae177d216cd029a1d16cb3983',1,'Ruyi::SDK::SDKValidator::ValidatorServiceMultiface::ValidatorServiceMultiface()']]],
  ['validatorserviceprocessor',['ValidatorServiceProcessor',['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service_processor.html#a0647ed51f7bb68899355aa54f38c5769',1,'Ruyi::SDK::SDKValidator::ValidatorServiceProcessor']]],
  ['validatorserviceprocessorfactory',['ValidatorServiceProcessorFactory',['../class_ruyi_1_1_s_d_k_1_1_s_d_k_validator_1_1_validator_service_processor_factory.html#ac1cc599fc3731b298c2caa58e1e854eb',1,'Ruyi::SDK::SDKValidator::ValidatorServiceProcessorFactory']]]
];
